apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: kh-test21
  labels:
    app.kubernetes.io/name: kh-test21
    app.kubernetes.io/part-of: kh-test21-project
    kubernetes.azure.com/generator: devhub
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: kh-test21