apiVersion: v1
kind: Service
metadata:
  name: kh-test21
  namespace: sample-app-namespace-1751386090857
  labels:
    app.kubernetes.io/name: kh-test21
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: kh-test21
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80