apiVersion: v1
kind: Service
metadata:
  name: test-build
  namespace: namespace-workflow-1746503700173
  labels:
    app.kubernetes.io/name: test-build
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: test-build
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000