apiVersion: v1
kind: ConfigMap
metadata:
  name: kenh-workflow-config
  namespace: namespace-workflow-1743184283472
  labels:
    app.kubernetes.io/name: kenh-workflow
    kubernetes.azure.com/generator: devhub
data: