apiVersion: v1
kind: ConfigMap
metadata:
  name: test5-config
  namespace: namespace-workflow-1743113596545
  labels:
    app.kubernetes.io/name: test5
    kubernetes.azure.com/generator: devhub
data: