apiVersion: v1
kind: Service
metadata:
  name: kenh
  namespace: namespace-workflow-1743188058673
  labels:
    app.kubernetes.io/name: kenh
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: kenh
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80