apiVersion: v1
kind: Service
metadata:
  name: kenh-workflow
  namespace: namespace-workflow-1743184283472
  labels:
    app.kubernetes.io/name: kenh-workflow
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: kenh-workflow
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000